services:

  # =====================================================
  # Python Backend
  # =====================================================
  python:
    build: ./docker/backend
    container_name: ${BACKEND_HOST}
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - ./backend:/var/www/app
    networks:
      - proxy
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy  # ✅ Attend que postgres soit prêt
      mongo:
        condition: service_healthy  # ✅ Attend que mongo soit prêt
      # redis:
      #   condition: service_healthy  # ✅ Attend que redis soit prêt  

  # =====================================================
  # React Frontend
  # =====================================================  
  react:
    build: ./docker/frontend
    container_name: ${FRONTEND_HOST}
    ports:
        - "${FRONTEND_PORT}:3000"
    volumes:
        - ./frontend:/var/www/app
    networks:
      - proxy
    restart: unless-stopped

  # =====================================================
  # PostgreSQL Database
  # =====================================================
  postgres:
    image: postgres:17-bookworm
    container_name: ${POSTGRES_HOST}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - proxy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: ${POSTGRES_HEALTHCHECK_INTERVAL}
      timeout: ${POSTGRES_HEALTHCHECK_TIMEOUT}
      retries: ${POSTGRES_HEALTHCHECK_RETRIES}

  # =====================================================
  # pgAdmin - Database Admin
  # =====================================================
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${PGADMIN_HOST}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - proxy
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      
  # =====================================================
  # MongoDb Database
  # =====================================================
  mongo:
    image: mongo
    container_name: ${MONGO_HOST}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongodb_data:/data/db
      - ./docker/database/mongodb_setup_v3.js:/mongodb_setup_v3.js           
    networks:
      - proxy
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:${MONGO_PORT}/${MONGO_DB} --quiet
      interval: ${MONGO_HEALTHCHECK_INTERVAL}
      timeout: ${MONGO_HEALTHCHECK_TIMEOUT}
      retries: ${MONGO_HEALTHCHECK_RETRIES}

  # =====================================================
  # Mongo-Express Database Admin
  # =====================================================
  mongo-express:
    image: mongo-express:latest
    container_name: ${MONGO_EXPRESS_HOST}
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST}                               # MongoDB container name
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}                                 # MongoDB port
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}                   # MongoDB admin username
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}               # MongoDB admin password
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_DB}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}                   # Mongo-express web username
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}               # Mongo-express web password
      ME_CONFIG_MONGODB_ENABLE_ADMIN: ${MONGO_EXPRESS_ENABLE_ADMIN}         # Access to all databases
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    volumes:     
      - ./docker/database/mongodb_setup_v3.js:/mongodb_setup_v3.js           
    networks:
      - proxy
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    # command: mongo --host ${MONGO_HOST} --port ${MONGO_PORT} --authenticationDatabase "admin" -u "${MONGO_ROOT_USER}" -p "${MONGO_ROOT_PASSWORD}" < mongodb_setup_v3.js

volumes:
  postgres_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: ./data/postgres
      o: bind
  pgadmin_data:
    driver: local
  mongodb_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: ./data/mongodb
      o: bind

networks:
  proxy:
    name: ${PROXY_NETWORK_NAME}
    driver: bridge
    external: true